[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.22"

[features]
seeds = false
skip-lint = false

[programs.localnet]
makora_vault = "BTAd1ghiv4jKd4kREh14jCtHrVG6zDFNgLRNoF9pUgqw"
makora_strategy = "EH5sixTHAoLsdFox1bR3YUqgwf5VuX2BdXFew5wTE6dj"
makora_privacy = "C1qXFsB6oJgZLQnXwRi9mwrm3QshKMU8kGGUZTAa9xcM"

[programs.devnet]
makora_vault = "BTAd1ghiv4jKd4kREh14jCtHrVG6zDFNgLRNoF9pUgqw"
makora_strategy = "EH5sixTHAoLsdFox1bR3YUqgwf5VuX2BdXFew5wTE6dj"
makora_privacy = "C1qXFsB6oJgZLQnXwRi9mwrm3QshKMU8kGGUZTAa9xcM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run test:programs"

[test]
startup_wait = 5000
shutdown_wait = 2000
